export const CART_ACTION = {
  ADD_ITEM: 'CART_ACTION_ADD_ITEM',
  REMOVE_ITEM: 'CART_ACTION_REMOVE_ITEM',
  SAVE_SHIPPING_ADDRESS: 'CART_ACTION_SAVE_SHIPPING_ADDRESS',
  SAVE_PAYMENT_METHOD: 'CART_ACTION_SAVE_PAYMENT_METHOD',
  RESET: 'CART_ACTION_RESET',
};
