export const ORDER_CREATE = {
  INITIAL: 'ORDER_CREATE_INITIAL',
  AWAIT: 'ORDER_CREATE_AWAIT',
  SUCCESS: 'ORDER_CREATE_SUCCESS',
  FAIL: 'ORDER_CREATE_FAIL',
};

export const ORDER_DETAILS = {
  AWAIT: 'ORDER_DETAILS_AWAIT',
  SUCCESS: 'ORDER_DETAILS_SUCCESS',
  FAIL: 'ORDER_DETAILS_FAIL',
};

export const ORDER_PAY = {
  AWAIT: 'ORDER_PAY_AWAIT',
  SUCCESS: 'ORDER_PAY_SUCCESS',
  FAIL: 'ORDER_PAY_FAIL',
  RESET: 'ORDER_PAY_RESET',
};

export const ORDER_DELIVERED = {
  AWAIT: 'ORDER_DELIVERED_AWAIT',
  SUCCESS: 'ORDER_DELIVERED_SUCCESS',
  FAIL: 'ORDER_DELIVERED_FAIL',
  RESET: 'ORDER_DELIVERED_RESET',
};

export const ORDER_LIST_MY = {
  AWAIT: 'ORDER_LIST_MY_AWAIT',
  SUCCESS: 'ORDER_LIST_MY_SUCCESS',
  FAIL: 'ORDER_LIST_MY_FAIL',
  RESET: 'ORDER_LIST_MY_RESET',
};

export const ORDER_LIST = {
  AWAIT: 'ORDER_LIST_AWAIT',
  SUCCESS: 'ORDER_LIST_SUCCESS',
  FAIL: 'ORDER_LIST_FAIL',
};
