export const PRODUCT_LIST_REQUEST = {
  AWAIT: 'PRODUCT_LIST_AWAIT',
  SUCCESS: 'PRODUCT_LIST_SUCCESS',
  FAIL: 'PRODUCT_LIST_FAIL',
};

export const PRODUCT_DETAIL_REQUEST = {
  AWAIT: 'PRODUCT_DETAIL_AWAIT',
  SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
  FAIL: 'PRODUCT_DETAIL_FAIL',
  RESET: 'PRODUCT_DETAIL_RESET',
};

export const PRODUCT_DELETE_REQUEST = {
  AWAIT: 'PRODUCT_DELETE_AWAIT',
  SUCCESS: 'PRODUCT_DELETE_SUCCESS',
  FAIL: 'PRODUCT_DELETE_FAIL',
};

export const PRODUCT_CREATE_REQUEST = {
  AWAIT: 'PRODUCT_CREATE_AWAIT',
  SUCCESS: 'PRODUCT_CREATE_SUCCESS',
  FAIL: 'PRODUCT_CREATE_FAIL',
  RESET: 'PRODUCT_CREATE_RESET',
};

export const PRODUCT_EDIT_REQUEST = {
  AWAIT: 'PRODUCT_EDIT_AWAIT',
  SUCCESS: 'PRODUCT_EDIT_SUCCESS',
  FAIL: 'PRODUCT_EDIT_FAIL',
  RESET: 'PRODUCT_EDIT_RESET',
};

export const PRODUCT_CREATE_REVIEW = {
  AWAIT: 'PRODUCT_CREATE_REVIEW_AWAIT',
  SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
  FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
  RESET: 'PRODUCT_CREATE_REVIEW_RESET',
};

export const PRODUCT_TOP = {
  AWAIT: 'PRODUCT_TOP_AWAIT',
  SUCCESS: 'PRODUCT_TOP_SUCCESS',
  FAIL: 'PRODUCT_TOP_FAIL',
};
