export const USER_LOGIN = {
  AWAIT: 'USER_LOGIN_AWAIT',
  SUCCESS: 'USER_LOGIN_SUCCESS',
  FAIL: 'USER_LOGIN_FAIL',
};

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER = {
  AWAIT: 'USER_REGISTER_AWAIT',
  SUCCESS: 'USER_REGISTER_SUCCESS',
  FAIL: 'USER_REGISTER_FAIL',
};

export const USER_DETAILS = {
  AWAIT: 'USER_DETAILS_AWAIT',
  SUCCESS: 'USER_DETAILS_SUCCESS',
  FAIL: 'USER_DETAILS_FAIL',
  RESET: 'USER_DETAILS_RESET',
};

export const USER_UPDATE_PROFILE = {
  AWAIT: 'USER_UPDATE_PROFILE_AWAIT',
  SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
  FAIL: 'USER_UPDATE_PROFILE_FAIL',
  RESET: 'USER_UPDATE_PROFILE_RESET',
};

export const USER_LIST = {
  AWAIT: 'USER_LIST_AWAIT',
  SUCCESS: 'USER_LIST_SUCCESS',
  FAIL: 'USER_LIST_FAIL',
  RESET: 'USER_LIST_RESET',
};

export const USER_DELETE = {
  AWAIT: 'USER_DELETE_AWAIT',
  SUCCESS: 'USER_DELETE_SUCCESS',
  FAIL: 'USER_DELETE_FAIL',
};

export const USER_EDIT = {
  AWAIT: 'USER_EDIT_AWAIT',
  SUCCESS: 'USER_EDIT_SUCCESS',
  FAIL: 'USER_EDIT_FAIL',
  RESET: 'USER_EDIT_RESET',
};
