export const VOUCHER_LIST_REQUEST = {
  AWAIT: 'VOUCHER_LIST_AWAIT',
  SUCCESS: 'VOUCHER_LIST_SUCCESS',
  FAIL: 'VOUCHER_LIST_FAIL',
};

export const VOUCHER_DELETE_REQUEST = {
  AWAIT: 'VOUCHER_DELETE_AWAIT',
  SUCCESS: 'VOUCHER_DELETE_SUCCESS',
  FAIL: 'VOUCHER_DELETE_FAIL',
};

export const VOUCHER_CREATE_REQUEST = {
  AWAIT: 'VOUCHER_CREATE_AWAIT',
  SUCCESS: 'VOUCHER_CREATE_SUCCESS',
  FAIL: 'VOUCHER_CREATE_FAIL',
  RESET: 'VOUCHER_CREATE_RESET',
};

export const VOUCHER_EDIT_REQUEST = {
  AWAIT: 'VOUCHER_EDIT_AWAIT',
  SUCCESS: 'VOUCHER_EDIT_SUCCESS',
  FAIL: 'VOUCHER_EDIT_FAIL',
  RESET: 'VOUCHER_EDIT_RESET',
};
